### ISSUE TITLE
regression: pointer not updated on non-warpd move when in normal mode

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/warp#105]
Hello,

I just noticed that since commit 6087329e44968ca0b2fe4296066c3b90d0b9712b, pointer moves on X with a non-warpd input device such as a physical mouse while in normal mode are shown visually (i.e. the red dot moves) only after the next warpd move has occured. I also managed to confuse warpd several times by external pointer movements so that upon the next warpd movement the red dot was permanently trapped in the upper or lower left corner.

The problem seems to be that `mouse_process_key` no longer returns `1` unconditionally, so that the `redraw` in the if-statement on line 48 of `normal.c` no longer fires. I could solve this by inserting another redraw but am quite sure that it is not at the optimal position (and also don't have an explanation for the pointer becoming trapped sometimes, maybe some unexpected large change of coordinates?), therefore this issue instead of a pull request.

**Comment by rvaiya** [comment]
The fact that this ever worked at all is a bug. The user is expected to use warpd to exclusively manipulate the pointer while it is active.

**Comment by rvaiya** [comment]
This is only a problem if you try and use the mouse while warpd is running ;).  I am inclined to just treat this as undefined behaviour. 

The practical reason for this is that not all platforms (e.g wayland) offer a way to obtain global pointer coordinates, so warpd has to keep track of them internally. One solution might be to enforce this by disabling the mouse while warpd is active, but I'm too lazy to do that for each platform (and it may not be possible anyway).

**Comment by rvaiya** [comment]
> I see, but couldn't a practical (and easy to implement) solution be to save pointer coordinates every time all movement keys are released and then restore them when such a key is pressed the next time?

Sure, but this will just hide the fundamental incompatibility a bit better. I'm not sure it solves a usability problem. This is already the default behaviour on wayland, since the platform code keeps track of pointer coordinates, but since the real cursor can't be hidden there is an additional visual discrepancy.

Ultimately it is easier to just treat it as undefined behaviour than to try and figure out what each platform will do. The other alternative is to try and add cross platform support for it.
