### ISSUE TITLE
accelerator again: parameter reset after release intended?

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/warp#131]
One more thing regarding the accelerator: Is it intended that after releasing it while continuing to hold a move button, the speed and acceleration values are reset (i.e. the cursor starts moving as if one released the move button as well and pressed it again)? Before submitting today's pull request, I was using my earlier implementation (temporary speed override while accelerating in the background) and now the sudden “brake”-effect after releasing the accelerator feels a bit unnatural.

I think it would be sensible as well to have the following behaviour:

When releasing the accelerator, the acceleration value is set to the value it would be if the accelerator had never been pressed and the currently reached cursor speed is kept.

I hope it is understandable what I mean, otherwise please let me know.

**Comment by rvaiya** [comment]
This is by design. 

One could argue it is less natural in the sense that physical objects don't behave that way, but I would argue it is more useful given that the intended use is allowing the user to intermittently accelerate the pointer whilst doing some local manipulation. 

It is better to think of the 'accelerator' as a speed toggle which happens to have an acceleration curve.
