### ISSUE TITLE
bug: clashes of certain identical keybindings

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/warp#149]
Certain user keybindings for normal mode which are bound to some other action by default execute both the user bound action and the default one. Two such examples are custom bound` accelerator and decelerator keys which coincide with the history key.

The problem comes from the two long, separate if-else statements in the normal_mode loop, which are both entered on a keypress. My naive fix would be to  connect the second block starting at line 115 in normal.c to the previous one, but probably there is a reason to keep them seperate.

**Comment by rvaiya** [comment]
This is a known bug. The current advice is to leave it up to the user to detect and manage conflicts (by (re/un)assigning conflicting bindings if necessary), though it is acknowledged that this is suboptimal.

> Here is a rough explanation of what I have in mind:
> [...]

This is probably the correct approach. 

The original config parsing logic was generated by a python script and originally written when warpd was much simpler, the C implementation was written as a straightforward replacement for the generated logic without adding any additional validation (ostensibly for simplicity, but mainly because I was lazy). 

For the time being I am trying to avoid making major changes to warpd, since I have decided to devote my attention to the keyd implementation which may (or may not) ultimately end up deprecating warpd. There are several problems inherent in warpd's design which can't be solved without a complete redesign anyway.

**Comment by rvaiya** [comment]
I thought about it a bit more and realized this is sufficiently vexing to warrant some effort. 

The latest commit adds proper config shadowing on a per mode basis so the user can just define the keys of interest without worrying about what is already bound.

> I'm getting more and more excited about your keyd implementation! So given that there are major changes approaching, I will also live with this bug and try to stop raising issues for the time
being (although this might be hard).

In truth I haven't invested much time in it yet, but it is on my todo list :P. Hopefully once the warpd bug requests cease I can devote more attention to it ;).

> But even when all features have been integrated into keyd, I actually don't think that the standalone tool will end up deprecated. It will still have its uses for scripting.

This is likely true, though it will depend on the extent to which I end up fleshing out the client side code.
