### ISSUE TITLE
the future of warpd and its integration into keyd

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/warp#154]
When hearing about your plans about the planned integration of warpd into keyd, I took a step back and thought about warpd's recent development (which has been quite rapid and impressive over the last months), as well as a possible future path to take. This was also a wonderful way to procrastinate as I have rather unpleasant paperwork to do. Here I'm sharing my thoughts to spark some discussion.

First of all, apart from their merit from an end user perspective, all the new features have also brought a considerable increase in complexity and made warpd violate the unix philosophy (I will give examples later, including the “correct” ways the same functionality can be achieved), which at least from my point of view should be followed at all costs. Of course I take full responsibility for these violations, as it was often me who persistently lobbied for these features.

So here is a proposition for redesigning/refactoring (the command and library names are of course up to debate and just for having something to refer to in this discussion):

# Core libraries

- `vmouse`: a low level (evdev/uinput) library emulating a virtual mouse, implementing clicking, proper pointer movement and scrolling. Proper here means pointer and scroll speed acceleration/deceleration support. The routines to move the pointer or scroll should keep an internal static speed multiplier (controlling the rate with which the corresponding mouse events are emitted), which increases and decreases only depending on the number of `move` or `scroll` method calls within a certain time frame. Currently, keyd has rudimentary support for this in the `vkbd` interface, I think that all the `vkbd_mouse_*` routines should be split off and be refined, together with routines for controlling the scroll speed and pointer acceleration parameters.

- `libwarp`: a library offering routines to efficiently move the pointer to an arbitrary point on the screen(s). Everything here should of course assume some graphical environment. This is where current hint, hint2, hintspec and grid-functionality should go. Routines simply start the required selection mode and return the obtained coordinates.

The two `vmouse` and `libwarp` libraries would serve as a backend for a simplified `warpd` (see below), while keyd would exclusively make use of `vmouse`, integrating all other functionality via `command()`.

# Integration of keyd with vmouse

One could implement

- mouse move and scroll keys (the latter are currently not present if I'm not mistaken), which behave exactly as their counterparts in warpd's current normal mode.

- actions which allow manipulating all parameters for scroll speed and movement acceleration/deceleration, either while held or permanently (like `layer()` and `toggle_layer()` but for the parameters instead of layers). For example to implement an accelerator button, one could then simply bind it to `set_acceleration_speed(val)` action.

- ability to set the above parameters in the global section

- mouse click keys which are only depressed upon key release (could be implemented internally via a `mouse_click()` action) as well as an action to lock a mouse button (keep it pressed until the action is called again). Both is needed for dragging.

# Tools to integrate cursor warping into keyd and shell scripts

The following two command line tools should be implemented. Building upon these, all variations of the current special warpd modes (with or without clicking etc.) could then be implemented via simple shell scripts, which in turn can be integrated into keyd via `command()`.

- `hintsel`: a command line tool using `libwarp`, which draws predefined hints on screen, prints the selected coordinates to STDOUT. Hintsets can be fed to STDIN or alternatively given in a file (via a respective option). Parameters such as hintchars, undo, undo_all and exit keys, colors, font etc. should all be specified in a configuration file and in addition as command line options. In my opinion, this is the distinguishing feature of current warpd.

- `gridsel` (if you still want to continue supporting this inferior mode): same as `hintsel`, but for grid mode.

- a supporting tool for `hintsel` which generates a configurable hint grid (covering all or parts of the screen, local around a given coordinate as in the second pass of current hint2 mode etc.) to be consumed by hintsel.

- `vmouse`: a command line tool named after the library it uses, which does cursor movement, scrolling and clicking with predefined keys and exits as soon as any other key is pressed, printing the pressed key to STDOUT.

- `warp`, `ppos` and `click`: Somewhat lighter alternatives to `xdotool` and the likes, which set/get pointer coordinates and click a given button. Of course, all of these tools have nothing to do with warpd or keyd and several of the trivial implementations already exist under different names, I'm just writing it here for completeness.

# Warpd functionality not present via the above setup

- *history* (including `--record`): Should be independent of the mouse used and delegated to an external daemon (monitoring the core pointer) if desired.

# What should happen to current warpd?

With the above setup, all of the current warpd functionality can be achieved via keyd with a much improved user experience. Instead of activating current warpd's normal mode, one could now simply toggle a mouse layer (no exit key needed), which could not only act precisely as the current warpd normal mode, but at the same time would be much more customizable (specialized commands for certain tasks etc.). Therefore, a `warpd` tool similar to its current form would probably only be of value to non-keyd users, in particular those running MacOS.

In any case, it should be stripped of all scripting features (such as
`--move`, `--click`, `--record`, `--query`, the oneshot modes, print keys and arguably also the activation keys (which is the job of a hotkey daemon, and even on Mac one can set custom keyboard shortcuts). What remains would basically be a glorified wrapper of the above tools, which could alternatively be implemented in a simple shell script. Most of development time should be given to two core libraries, which would have to regularly adapt to changing desktop environments.

# Should warpd run as a daemon?

This is an important question to answer. The only advantage I see are the speed improvements related to hint caching you have mentioned in another thread.

From my point of view, the only important goal should be no noticeable lag for the end user, and this can also be achieved without having a daemon running (I tested on a ten year old notebook with a very large amount of hints). Of course, things might be different on MacOS though.

So I think that from an end user point of view, running as a daemon basically only provides the convenience of managing the activation keys for the single modes in a centralized place (which is not the job of warpd). Therefore, I vouch against continuing to run it as a daemon and instead just bind the activation keys to the appropriate calls via an external hotkey daemon.

# Final words

What ever decision will be taken, I'll be very happy to help with development and any other necessary support. As I have already mentioned many times before, warpd and keyd (which I discovered and started using at the same time) had a similarly dramatic effect on my workflow as ditching windows in favour of *BSD/Linux many decades ago, and that's no exaggeration. They easily save me several hours of work time every week. So again, thank you very much for making them available to the public!

**Comment by rvaiya** [comment]
Thanks for taking the time to write this, and apologies for taking so long to respond (though it is a bit of a mammoth ;)).

> vmouse
> [...]
> libwarp

I'm not sure these represent the appropriate level of abstraction or provide enough value to warrant maintaining as separate libraries. Anyone writing similar software of sufficient complexity would probably be better off using the native kernel/X apis.

My priority at the moment is a macos port of keyd (which I haven't had much time to work on), after which I will probably add some preliminary mouse support and ultimately hint selection. I've probably been a bit premature in stating my intentions.

> The two vmouse and libwarp libraries would serve as a backend for a simplified
> warpd (see below), while keyd would exclusively make use of vmouse, integrating
> all other functionality via command().

This would effectively amount to a rewrite and would necessitate root access. I am more inclined to put warpd in maintenance mode and focus efforts on integrating hints into keyd.

> Actions which allow manipulating all parameters for scroll speed and movement acceleration/deceleration

This is on the horizon. I already have a small personal project to manage my trackballs called [moused](https://github.com/rvaiya/moused) which does this. My intention is to integrate most if its functionality into keyd.

> warp, ppos and click: Somewhat lighter alternatives to xdotool and the likes
> ...

Similar ideas have already been discussed in various issues. I have some reservations concerning the potential security implications, but I will probably end up extending the keyd client to allow for this in some form.

> hintsel: a command line tool using libwarp

This will likely be an extension of the above once hints have been implemented.

> With the above setup, all of the current warpd functionality can be
> achieved via keyd with a much improved user experience.
>[...]

The goal is indeed to provide the minimal set of features necessary to replicate most warpd's useful functionality, but keyd is unlikely to reach feature parity with warpd as it currently exists. The precise set of primitives will precipitate from the development process.

> Should warpd run as a daemon?  This is an important question to answer.

I think that ship has sailed :P.

> From my point of view, the only important goal should be no noticeable lag for the end user.

This was the original reason it was implemented thusly, but I have since come to believe that it is in fact a feature, not a bug, since some desktop environments make it unreasonably difficult to bind keys to commands. 

> I tested on a ten year old notebook with a very large amount of hints.

This has been partially enabled by subsequent changes to the drawing logic but, if memory serves, it was originally necessitated by the border radius logic (setting border radius slows down hint drawing considerably). The X shape extension doesn't seem to like non rectangular regions 

> I vouch against continuing to run it as a daemon and instead just bind the
> activation keys to the appropriate calls via an external hotkey daemon.

I am sympathetic to this line of reasoning, but I don't plan to break backwards compatibility at this point and it is already possible to use daemonlessly if the user desires.

> Final words What ever decision will be taken, I'll be very happy to help with
> development and any other necessary support.

I appreciate the offer, but most of my time is spent thinking about the design and wrestling with system APIs rather than writing code. For better or worse, I tend to be more of a cathedral builder by nature :P. Your issue contributions are already greatly appreciated.

> They easily save me several hours of work time every week. 

This is the greatest compliment one can hope to receive :).

> [...]
> Therefore, a better solution could be that keyd offers control of its virtual pointer and keyboard via its existing IPC mechanism. 

The final implementation will likely end up involving some kind of IPC protocol, but I'm not sure what the boundary will look like yet.
