### ISSUE TITLE
Repeated mousekeys cause drawing problems

### ISSUE THREAD

**Issue by wearpants** [rvaiya/warp#8]
Holding down the warp key or directional mousekey causes the grid and dot to disappear; it'll reappear after releasing and pressing again. Works fine if slowly tapping.

**Comment by wearpants** [comment]
happens with both movement & warp, description updated

**Comment by rvaiya** [comment]
To clarify, are you saying that the grid disappears even after you have released a movement key? If so, I was unable to reproduce the issue (see the linked video). If you simply mean that the grid flickers as you hold down a key then that is expected behaviour. I am abusing X windows to draw the mouse decorations which is bound to involve some latency and hence flicker. If it is enough of a nuisance I may look into optimizing this using compositing or fake transparency but I find it the current implementation quite usable at the moment. Having said that, it was designed for small movements of the kind you describe (since the grid is supposed to do most of the work).  If you find yourself holding down a movement key I daresay you're using it wrong :P.

Demo

https://vaiya.org/warp_1.mp4

**Comment by rvaiya** [comment]
To clarify, are you saying that the grid disappears even after you have released a movement key? If so I was unable to reproduce the issue (see the linked video). If you simply mean that the grid flickers as you hold down a key then that is expected behaviour. I am abusing X windows to draw the mouse decorations which is bound to involve some latency and consequently flicker. If it is enough of a nuisance I may look into optimizing the drawing code using compositing or fake transparency but I find it the current implementation quite usable. Having said that, the feature was designed for small movements (since the grid is supposed to do most of the work).  If you find yourself holding down a movement key I daresay you're using it wrong :P.

Demo

https://vaiya.org/warp_1.mp4

**Comment by rvaiya** [comment]
You might also want to consider disabling the xfce compositor which can introduce quite a bit of latency. I didn't experience any issues with grid while it was turned on but hints mode is definitely affected by it. It should also make your desktop quite a fair bit snappier (at the expense of some eye candy ;)).

**Comment by rvaiya** [comment]
You might also want to consider disabling the xfce compositor which can introduce quite a bit of latency. I didn't experience any issues with grid while it was turned on but hints mode is definitely affected by it. It should also make your desktop a fair bit snappier (at the expense of some eye candy ;)).

**Comment by wearpants** [comment]
Oh yup, problem was the compositor, thought I had turned it off already, I hate all that fancy eye candy.
