### ISSUE TITLE
Key mappings for scollwheel buttons

### ISSUE THREAD

**Issue by wearpants** [rvaiya/warp#9]
Think this was supported in pre-rewrite version? Would be helpful

**Comment by rvaiya** [comment]
This should work now. X interprets scroll events as button presses ('buttons' 4/5 are used for scrolling). I had previously allowed for an arbitrary number of mouse buttons to be mapped which inadvertently  facilitated scrolling but that was unintentional (I usually focus on a program and use arrow kesy). I've since reverted to the old behaviour (there is now a single 'buttons' config options).
